### PR TITLE
Lock the angular version on the resolution besides its minor version.

### PR DESCRIPTION
**Pull request by ordavidil**
#82

### CODE REVIEW

**Comment by amitaibu** [comment]
This looks as the opposite of locking - if there is a working version, I'd prefer to explicitly write that version.

**Comment by amitaibu** [comment]
This should be improved, but it's already fixing the tests

**Comment by amitaibu** [comment]
Merged, thanks.

**Comment by ordavidil** [comment]
@amitaibu 
Thanks :-)

I'll create a new PR that actually lock the versions later this week...

**Pull request merged**
