### PR TITLE
Update modules versions.

### PR DESCRIPTION
**Pull request by nirgn975**
#79

### CODE REVIEW

**Comment by nirgn975** [comment]
@amitaibu Ready for code review.

**Comment by amitaibu** [comment]
Thanks. Was all the content also migrated properly?

**Comment by nirgn975** [comment]
Yes it is.
selection_003

**Comment by amitaibu** [comment]
Tests are failing - can you please check

**Comment by amitaibu** [comment]
@nirgn975 can you re-roll please, I believe @ordavidil has fixed the tests

**Comment by ordavidil** [comment]
yes,
@nirgn975 
Check the _bower.json_ file. You can improve it by setting the angular version to `1.3.20` instead of using the `~` sign as I did.

```JS
// bower.json ...

  "resolutions": {
    "angular": "1.3.16"
  }
```

**Comment by nirgn975** [comment]
@amitaibu Done.

**Comment by amitaibu** [comment]
Thanks. Published `v1.1.0`

**Pull request merged**
